### PR TITLE
[WIP] Documentation editing pass

### LINKED ISSUE #43: Documentation editing pass
Does anyone mind if I do an editor's pass on the documentation? The purpose is to fix grammar, spelling, etc. Not to make substantive changes.

I'd also like to thank whoever submitted the documentation and apologize for English following the big ball of mud (non-)design pattern.

### PR DESCRIPTION
**Pull request by kspeakman**
resolves #43 

Worked thru the index page so far.

### CODE REVIEW

**Comment by kspeakman** [comment]
This is about all I can find in this repo as far as English technicalities.

It could be worthwhile to change the Elmish selling point. It only mentions Fable apps. But Elmish can be used in other contexts. Maybe update it to match the Elmish repo's docs. It's a change in message, so I didn't want to do that without mentioning it first.

**Comment by et1975** [comment]
Please feel free to change the message!

**Comment by MangelMaxime** [comment]
@kspeakman Small question

I always find it strange when people using `Project Ressources` instead of `Project ressources` for sections tiles or element in a list.

Is this an English thing? American thing?

Just asking because I always end up not knowing which one to choose or why 😅

**Comment by kspeakman** [comment]
@MangelMaxime It's part of the English (US) capitalization rules for titles. Basically everything gets capitalized except joining words. Not capitalized are: articles like `a`, `an`, `the`; conjunctions like `and`, `or`; prepositions like `in`, `for`, `to`. Even those are capitalized if they are the first word of the title. Not all rules are agreed upon by everybody. (Grammarly says some references capitalize conjunctions and prepositions.) And for aesthetics, you can use the concept of artistic license. Meaning ignore the rules if it complements your visuals. For example, some sites use all lower case for menu items and titles to complement their minimalistic design.

Edit: I wasn't taught British English, but I've observed that most of the English language rules are the same. The only difference I can think of is that British English treats collective nouns as plural. So "Nvidia are price gouging" vs US "Nvidia is price gouging". What's most different about them is the content: the phrases and words used. Plus some minor spelling differences. (Not to mention the speaking differences.)

**Comment by MangelMaxime** [comment]
@kspeakman Thank you for the detailed explanations

**Comment by kspeakman** [comment]
I think these changes are good to merge. Let me know if I missed something.

**Review by et1975 — APPROVED** [review]

**Pull request merged**
